name: jpush_flutter_plugin_android
description: Android implementation of the `jpush_flutter_plugin` that implements `jpush`'s message push service.
repository: https://github.com/kimmy214/jpush_flutter_plugin/tree/main/jpush_flutter_plugin_android
version: 0.0.1-alpha.1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.2"

flutter:
  plugin:
    implements: jpush_flutter_plugin
    platforms:
      android:
        package: me.kimmy.plugins.jpushflutterplugin
        pluginClass: JpushFlutterPluginPlugin
        dartPluginClass: JpushFlutterPluginAndroid

dependencies:
  flutter:
    sdk: flutter
  jpush_flutter_plugin_platform_interface: ^0.0.1-alpha.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^3.1.0
