name: jpush_flutter_plugin_platform_interface
description: A common platform interface for the `jpush_flutter_plugin` that implements `jpush`'s message push service.
repository: https://github.com/kimmy214/jpush_flutter_plugin/tree/main/jpush_flutter_plugin_platform_interface
version: 0.0.1-alpha.5

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.2"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.1.0
